# Generated by Django 4.1.1 on 2023-01-02 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petabanjir',
            old_name='judul',
            new_name='deskripsi',
        ),
    ]
