# Generated by Django 4.1.1 on 2023-01-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0002_rename_judul_petabanjir_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petabanjir',
            name='deskripsi',
            field=models.TextField(),
        ),
    ]
