# Generated by Django 4.1.1 on 2023-01-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgis', '0003_alter_petabanjir_deskripsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petabanjir',
            name='garis_bujur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petabanjir',
            name='garis_lintang',
            field=models.FloatField(),
        ),
    ]
